baseURL = "https://jaddious.github.io/site/"
languageCode = "en-us"
title = ""
theme = "PaperMod"

[params]
  description = "Architect, urban planner and researcher"
  author = "Jadd Hallaj"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true

[caches]
  [caches.images]
    dir = ":cacheDir/images"